sudo: required

language: generic

env:
  OS: linux

services:
  - docker

branches:
  only:
  - develop

install:
  - sudo cp ./bin/fin /usr/local/bin/fin && sudo chmod +x /usr/local/bin/fin
  - fin version
  - fin install tools
  - fin sysinfo

before_script:
  - git clone https://github.com/docksal/drupal7.git ../drupal7 && cd ../drupal7

script:
  - bats ../docksal/tests/start.bats
