sudo: required

language: generic

env:
  OS: linux

services:
  - docker

install:
  - sudo cp ./bin/fin /usr/local/bin/fin && sudo chmod +x /usr/local/bin/fin
  - fin version
  - export DOCKSAL_VERSION="$TRAVIS_BRANCH"
  - fin update
  - fin sysinfo

before_script:
  - git clone https://github.com/docksal/drupal8.git ../drupal8
  - mkdir ../test-config

script:
  # Testing Docksal system services
  - bats "tests/smoke-test-system.bats"
  # Test Docksal configuration system
  - cd "$TRAVIS_BUILD_DIR/../test-config"
  - bats "$TRAVIS_BUILD_DIR/tests/smoke-test-config.bats"
  # Test a project workflow
  - cd "$TRAVIS_BUILD_DIR/../drupal8"
  - bats "$TRAVIS_BUILD_DIR/tests/smoke-test-general.bats"
