# Docker and Docker Compose based environment for Drupal.
# See https://github.com/blinkreaction/docker-fig-drupal for more information and documentation.

# Web node
web:
  hostname: web
  image: blinkreaction/drupal-apache-php:2.2-5.5
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # PHP configuration overrides
    - "./.docker/etc/php5/php.ini:/etc/php5/fpm/conf.d/z_php.ini"
    # Drupal docroot mapping
    - "./docroot:/var/www"
  links:
    - db
    - memcached

# DB node
db:
  hostname: db
  image: blinkreaction/mysql:5.5
  ports:
    - "3306:3306"
  # DB configuration
  environment:
    - MYSQL_ROOT_PASSWORD=admin123
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=123
    - MYSQL_DATABASE=drupal
  volumes:
     # MySQL configuration overrides
     - "./.docker/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"
     # Permanent DB data storage
     - /var/lib/mysql

# Memcached node
memcached:
  hostname: memcached
  image: memcached
  environment:
    # Memcached memory limit in megabytes
    - MEMCACHED_MEMORY_LIMIT=128

