# Docker and Docker Compose based environment for Drupal.
# See https://github.com/docksal/docksal for more information and documentation.

version: "2"

services:
  # Web node
  web:
    hostname: web
    image: docksal/web:1.0-apache2.2
    volumes:
      # Project root volume
      - project_root:/var/www:ro
    labels:
      - io.docksal.virtual-host=${VIRTUAL_HOST}
      - io.docksal.project-root=${PROJECT_ROOT}
    environment:
      - APACHE_DOCUMENTROOT=/var/www/${DOCROOT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}

  # DB node
  db:
    hostname: db
    image: docksal/db:1.0-mysql-5.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=default

  # CLI node
  # Used for all console commands and tools.
  cli:
    hostname: cli
    image: docksal/cli:1.0-php7
    volumes:
      # Project root volume
      - project_root:/var/www:rw
      # Host home volume (for SSH keys and other credentials).
      - host_home:/.home:ro
      # Shared ssh-agent socket
      - docksal_ssh_agent:/.ssh-agent:ro
